# this is just a start, eventually I'd like to implement automated tests.
on:
  workflow_dispatch
#  push:
#    branches:
#    - main
#    - release/*
#  pull_request:
#    types: [opened, synchronize, reopened]
jobs:
  run_tests:
    name: Run automated tests
    runs-on: [self-hosted, Delphi]
    steps:
     - run: echo Hello World!
